[package]
name = "depviz"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde-xml-rs = "0.5.1"

[dependencies.uuid]
version = "1.11.0"
features = [
    "v4",                
    "fast-rng",         
    "macro-diagnostics", 
]